//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMAT1610PersonalWebsite.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMAT1610Entities2 : DbContext
    {
        public IMAT1610Entities2()
            : base("name=IMAT1610Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_UserActivity> tbl_UserActivity { get; set; }
        public DbSet<tbl_UserInfo> tbl_UserInfo { get; set; }
        public DbSet<tbl_UserLogin> tbl_UserLogin { get; set; }
    }
}
