//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMAT1610PersonalWebsite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserActivity
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string IPAddress { get; set; }
        public string ActivityDescription { get; set; }
        public string ActivityCategory { get; set; }
        public System.DateTime ActivityTimestamp { get; set; }
        public string SourcePnumber { get; set; }
    }
}
